# Generated by Django 5.0.6 on 2024-05-12 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('vendeur', 'Vendeur'), ('admin', 'Admin')], default='client', max_length=10),
        ),
    ]
